### ISSUE TITLE
No module named 'text_preprocessing'

### ISSUE THREAD

**Issue by NicolasBizzozzero** [ARTFL-Project/text-align#54]
Hello !  
I'm trying to run the command `textalign` right after successfully running the `install.sh` script, but the software rewards me with this error message :
```bash
$ textalign 
Traceback (most recent call last):
  File "/usr/local/bin/textalign", line 12, in <module>
    from textalign import TEIParser, Ngrams, create_web_app, web_loader, parse_config
  File "/usr/local/lib/python3.5/dist-packages/textalign/__init__.py", line 2, in <module>
    from .generate_ngrams import Ngrams
  File "/usr/local/lib/python3.5/dist-packages/textalign/generate_ngrams.py", line 19, in <module>
    from text_preprocessing import PreProcessor, modernize
ImportError: No module named 'text_preprocessing'
```
It seems that the module `text_preprocessing` has not been included in the `textalign` python package during my installation.  
Do you know how to fix this error ?  
Thank you for your time and have a great day !

**Comment by clovis** [comment]
Hi, yes this module was in a private repo until today. I just made it public but since it is still under heavy development, I'm not publishing it to pypi.  You can find it here:
https://github.com/ARTFL-Project/text-preprocessing
I will add it to the install.sh command so that it gets installed automatically.
